version: "2"
services:
  react: 
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
  web:
    build: .
    command: npm run start
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
